import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { FaGithub, FaLinkedin } from "react-icons/fa";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-black antialiased`}
      >
        {children}
        <footer className="bg-gray-800 text-gray-300 py-6 mt-8">
          <div className="container mx-auto flex flex-col md:flex-row justify-between items-center px-4">
            <p className="text-sm">&copy; {new Date().getFullYear()} Abdul. All rights reserved.</p>

            <div className="flex space-x-6">
              <a
                href="https://github.com/hannanghumsani"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-white transition-colors duration-300"
              >
                <FaGithub size={24} />
              </a>

              <a
                href="https://linkedin.com/in/abdul-hannan-a34a4922a"
                target="_blank"
                rel="noopener noreferrer"
                className="hover:text-white transition-colors duration-300"
              >
                <FaLinkedin size={24} />
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
